set nocompatible          " Use Vim defaults (much better!)
set bs=2                  " Allow backspacing over everything in insert mode
set ai                    " Always set auto-indenting on
set history=5000          " keep 5000 lines of command history
set ruler                 " Show the cursor position all the time
set number                " Show Line number

" Don't use Ex mode, use Q for formatting
map Q gq

" When doing tab completion, give the following files lower priority.
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo

set nomodeline
syntax on
autocmd BufRead APKBUILD set filetype=sh
